# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SyarahChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'Mixpanel-swift'
pod 'FirebaseRemoteConfig'
pod 'Amplitude'
pod 'Alamofire'
  # Pods for SyarahChallenge

  target 'SyarahChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SyarahChallengeUITests' do
    # Pods for testing
  end

end
